### ISSUE TITLE
What is the runame option?

### ISSUE THREAD

**Issue by adiakritos** [gzigzigzeo/ebay_request#21]
Hi!

Curious to know what the 'runame' option is. 

Thanks!

**Comment by nepalez** [comment]
It is the eBay-provided abbreviation for redirect uri name (`RuName`).
You can read about it here https://developer.ebay.com/api-docs/static/oauth-redirect-uri.html

**Comment by Envek** [comment]
In short: eBay doesn't allow to specify redirect URI directly for OAuth (where the user will be returned with authentication results) but instead requires you to register fixed redirect URI in your application's settings in the eBay Developers Program site and specify only its identifier in your app's configuration.

**Comment by jontarg** [comment]
Note that you don't need a "runame" if your app is for single-user purposes (e.g. you're managing listings for your store). You'll need to set that option to a non-empty value (so basic presence validation passes) and pass your previously generated via ebay dashboard token as an option to your API call:

```
EbayRequest.configure do |config|
  ...
  config.runame = 'notneeded!'
end

EbayRequest::Trading.new(token: your_auth_n_auth_token)
```

**Comment by dportalesr** [comment]
Note that you don't need a "runame" if your app is for single-user purposes (e.g. you're managing listings for your store). You'll need to set that option to any non-empty value (so basic presence validation passes) and pass your previously generated via ebay dashboard token as an option to your API call:

```
EbayRequest.configure do |config|
  ...
  config.runame = 'notneeded!'
end

EbayRequest::Trading.new(token: your_auth_n_auth_token)
```

**Comment by nepalez** [comment]
@dportalesr good point, thank you!
In fact, we heavily use the gem to send requests on behalf of many sellers, so this case was edgy )
